### ISSUE TITLE
[Offtopic] Это шикарно

### ISSUE THREAD

**Issue by vladkorotnev** [azya52/STMP#1]
Очень рад, что кто-то довёл всё-таки мою идею до конца!
Большое спасибо!

**Comment by vladkorotnev** [comment]
Как у получившегося модуля с потреблением, кстати? В своё время столкнулся, что при выключении калькулятора остаётся питание на картридже, хоть и чуть ниже (3.3 вместо 5) -- в итоге картридж не сбрасывался назад в автозапуск, жрал батарейку до кучи.

**Comment by azya52** [comment]
Спасибо! Ваш проект сильно помог.
С потреблением не очень хорошо - около 5мА и при разряженных аккумуляторах приходится включать на горячую, иначе мк90 не хочет запускаться с такой нагрузкой. Вообще я изначально планировал развести отдельную плату и использовать STM32F4, там есть встроенный POR/PDR - можно было бы уходить в сброс при падении напряжения и проблемы бы не было, к тому же в этой серии есть дешевые контроллеры с 512кб флеша (все же 128 маловато), но что-то меня программирование игр для него отвлекло.

**Comment by silensilen** [comment]
Спасибо за разработку!
Какой разъём/штекер Вы использовали для подключения к МК-90?

**Comment by azya52** [comment]
silensilen, я использовал обычный штырьевой разъем, чуть рассверлив отверстия. Что-то штатно подходящее у меня найти так и не получилось.

**Comment by silensilen** [comment]
> silensilen, я использовал обычный штырьевой разъем, чуть рассверлив отверстия. Что-то штатно подходящее у меня найти так и не получилось.

Да, я тоже, но не рассверливал, а перевернул  контакты на 90градусов и зафиксировал их клеем.
