### ISSUE TITLE
Firmware STMP.hex

### ISSUE THREAD

**Issue by dk1spb** [azya52/STMP#2]
Добрый день!
Заливаю прошивку - при подключении "A request for the USB device descriptor failed"
Пробую с другой прошивкой - всё норм, то есть, скорее всего, дело не в том что я неправильно прошиваю и не в устройстве.
Точно ли выложена рабочая прошивка?

**Comment by azya52** [comment]
Здравствуйте!
Прошу прощения, только сейчас увидел и то наткнувшись на ваше сообщение на phantom.sannata.org, что-то github не присылает уведомление о новых issues :(
Не знаю, актуально ли еще, но проверил сейчас - залил hex выложенный здесь - нормально определяется как USB. Может проблема в разных ревизиях/версиях Bluepill, у вас классическая плата на STM32F103C8T6? Как вариант, можете прогнать этот тест https://mecrisp-stellaris-folkdoc.sourceforge.io/bluepill-diagnostics-v1.6.html, возможно удастся выявить отличия в наших платах.

**Comment by azya52** [comment]
Все же была ошибка :( исправил.
